export enum WorkerRunnerErrorCode {
    CONNECTION_WAS_CLOSED = 'CONNECTION_WAS_CLOSED',

    RUNNER_NOT_FOUND = 'RUNNER_NOT_FOUND',
    RUNNER_INIT_ERROR = 'RUNNER_INIT_ERROR',
    RUNNER_EXECUTE_ERROR = 'RUNNER_EXECUTE_ERROR',
    RUNNER_DESTROY_ERROR = 'RUNNER_DESTROY_ERROR',

    HOST_DESTROY_ERROR = 'HOST_DESTROY_ERROR',

    UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',

    OTHER_ERROR = 'OTHER_ERROR',
}
