export enum WorkerRunnerNativeErrorCode {
    TYPE_ERROR = 'TYPE_ERROR',
    RANGE_ERROR = 'RANGE_ERROR',
    SYNTAX_ERROR = 'SYNTAX_ERROR',
    REFERENCE_ERROR = 'REFERENCE_ERROR',
    EVAL_ERROR = 'EVAL_ERROR',
    BASE_NATIVE_ERROR = 'BASE_NATIVE_ERROR',
}
