export enum WorkerErrorCode {
    RUNNER_INIT_CONSTRUCTOR_ERROR,
    RUNNER_INIT_CONSTRUCTOR_NOT_FOUND,

    RUNNER_EXECUTE_ERROR,
    RUNNER_EXECUTE_INSTANCE_NOT_FOUND,

    RUNNER_DESTROY_ERROR,
    RUNNER_DESTROY_INSTANCE_NOT_FOUND,
}