export const PROMISE_CONNECTION_IDENTIFIER_IFRAME_CLIENT = 'WORKER_RUNNER__PROMISE_IFRAME_CLIENT';
export const PROMISE_CONNECTION_IDENTIFIER_IFRAME_HOST = 'WORKER_RUNNER__PROMISE_IFRAME_HOST';
export const RX_CONNECTION_IDENTIFIER_IFRAME_CLIENT = 'WORKER_RUNNER__RX_IFRAME_CLIENT';
export const RX_CONNECTION_IDENTIFIER_IFRAME_HOST = 'WORKER_RUNNER__RX_IFRAME_HOST';

export const PROMISE_CONNECTION_IDENTIFIER_WORKER = 'WORKER_RUNNER__PROMISE_WORKER';
export const RX_CONNECTION_IDENTIFIER_WORKER = 'WORKER_RUNNER__RX_WORKER';
