name: Build CI

on: push

jobs:    
  tslint:

    name: TSlint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to commit
      uses: actions/checkout@v2
    - name: Set up node
      uses: actions/setup-node@v1
    - name: Install npm dependencies
      run: npm ci
    - name: Run TSLint
      run: npm run tslint
      env:
        CI: true
  
  build:

    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to commit
      uses: actions/checkout@v2
    - name: Set up node
      uses: actions/setup-node@v1
    - name: Install npm dependencies
      run: npm ci
    - name: Run Build
      run: npm run build
      env:
        CI: true
