name: Draft release

on:
  workflow_dispatch:
jobs:
  draft-release:

    name: Draft release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to commit
      uses: actions/checkout@v3
    - name: Set up node
      uses: actions/setup-node@v3
    - name: Get version from package.json
      run: echo "version=$(node -pe "require('./package.json').version")" >> $GITHUB_OUTPUT
      id: get_version
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ format('v{0}', steps.get_version.outputs.version) }}
        release_name: ${{ format('v{0}', steps.get_version.outputs.version) }}
        draft: true
