name: Publishing

on:
  release:
    types: [published]

jobs:
  publishing:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run publish
