name: Release publication

on:
  release:
    branches: [master]
    types: [published]

jobs:
  release-publication:

    name: Release publication
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to commit
      uses: actions/checkout@v2
    - name: Set up node
      uses: actions/setup-node@v2
      with:
        registry-url: https://registry.npmjs.org
    - name: Install npm dependencies
      run: npm ci
    - name: Run Build
      run: npm run build
    - name: Publish to npm repository
      run: npm run publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
