name: Test CI

on: [push, pull_request]

jobs:    
  test-chrome:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm ci
    - run: npm test -- --browsers ChromeHeadless
      env:
        CI: true
  
  test-firefox:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm ci
    - run: npm test -- --browsers FirefoxHeadless
      env:
        CI: true
