name: Versioning

on:
  push:
    branches: [master]

jobs:
  update-minor-version:

    name: Updating minor version
    if: startsWith(github.event.head_commit.message, 'Merge ') && !contains(github.event.head_commit.message, '[versioning skip]')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to commit
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUSH_TOKEN }}
    - name: Set up node
      uses: actions/setup-node@v1
    - name: Install npm dependencies
      run: npm ci
    - name: Configure commit author
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Updating version
      run: npm run version:minor
    - name: Push to a branch
      run: git push origin HEAD
