name: Versioning

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      update-type:
        required: true
        type: choice
        description: Version upgrade type
        options:
        - patch
        - minor
        - major
      author-name:
        required: false
        type: string
        description: Commit author name
      author-email:
        required: false
        type: string
        description: Commit author email

jobs:
  patch-version:
    name: Patch version
    if: |
      (github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'version:patch'))
      || (github.event_name == 'workflow_dispatch' && inputs.update-type == 'patch')
    uses: ./.github/workflows/update-version.yml
    with:
      update-type: patch
      author-name: ${{inputs.author-name}}
      author-email: ${{inputs.author-email}}

  minor-version:
    name: Minor version
    if: |
      (github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'version:minor'))
      || (github.event_name == 'workflow_dispatch' && inputs.update-type == 'minor')
    uses: ./.github/workflows/update-version.yml
    with:
      update-type: minor
      author-name: ${{inputs.author-name}}
      author-email: ${{inputs.author-email}}

  major-version:
    name: Major version
    if: |
      (github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'version:major'))
      || (github.event_name == 'workflow_dispatch' && inputs.update-type == 'major')
    uses: ./.github/workflows/update-version.yml
    with:
      update-type: major
      author-name: ${{inputs.author-name}}
      author-email: ${{inputs.author-email}}
